import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { BellRing, CalendarClock, Loader2, Plus, Trash2, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const typeLabels: Record<string, string> = { facilitation: "Animation", support: "Appui", logistics: "Logistique", nutrition: "Nutrition", supervision: "Supervision" };
const roleLabels: Record<string, string> = { facilitator: "Animateur", volunteer: "Volontaire" };

export default function ActivityAssignmentsPage() {
  const board = trpc.activities.assignmentBoard.useQuery();
  const utils = trpc.useUtils();
  const [activityId, setActivityId] = useState<string>("");
  const [staffId, setStaffId] = useState<string>("");
  const [assignmentType, setAssignmentType] = useState<"facilitation" | "support" | "logistics" | "nutrition" | "supervision">("support");
  const [assignmentFilter, setAssignmentFilter] = useState<"all" | "past" | "current" | "upcoming">("upcoming");
  const assign = trpc.activities.assignStaff.useMutation({ onSuccess: () => { toast.success("Affectation enregistrée et journalisée."); setStaffId(""); utils.activities.assignmentBoard.invalidate(); utils.dashboard.summary.invalidate(); }, onError: error => toast.error(error.message) });
  const remove = trpc.activities.removeStaffAssignment.useMutation({ onSuccess: () => { toast.success("Affectation retirée."); utils.activities.assignmentBoard.invalidate(); utils.dashboard.summary.invalidate(); }, onError: error => toast.error(error.message) });
  const reminderSettings = trpc.activityReminders.settings.useQuery();
  const [leadHours, setLeadHours] = useState("24");
  const configureReminders = trpc.activityReminders.configure.useMutation({ onSuccess: result => { toast.success(result.taskUid ? "Rappels internes activés." : "Rappels internes mis à jour."); reminderSettings.refetch(); }, onError: error => toast.error(error.message) });
  const data = board.data;
  const selectedActivity = useMemo(() => data?.activities.find(activity => activity.id === Number(activityId)), [activityId, data?.activities]);

  if (board.isLoading || !data) return <div className="grid h-72 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div>;
  const now = new Date();
  const allAssignments = data.assignments.filter(assignment => assignment.activityStartsAt).sort((a, b) => new Date(a.activityStartsAt!).getTime() - new Date(b.activityStartsAt!).getTime());
  const futureAssignments = allAssignments.filter(assignment => new Date(assignment.activityStartsAt!) > now);
  const visibleAssignments = allAssignments.filter(assignment => {
    const date = new Date(assignment.activityStartsAt!);
    if (assignmentFilter === "all") return true;
    if (assignmentFilter === "past") return date < new Date(now.getFullYear(), now.getMonth(), now.getDate());
    if (assignmentFilter === "current") return date.toDateString() === now.toDateString();
    return date >= new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1);
  });
  return <div className="space-y-6"><section className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">COORDINATION</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">Affectations d’activités</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Affectez les animateurs et volontaires aux activités. Ces liens déterminent leur tableau de bord et leurs rappels internes.</p></div><Badge variant="secondary" className="w-fit rounded-xl px-3 py-1.5">{futureAssignments.length} affectation(s) à venir</Badge></section>
    <Card className="surface-card"><CardHeader><p className="eyebrow">NOUVELLE AFFECTATION</p><CardTitle className="mt-1 text-lg">Ajouter un membre à une activité</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-4"><div className="space-y-2"><Label>Activité</Label><Select value={activityId} onValueChange={setActivityId}><SelectTrigger><SelectValue placeholder="Choisir une activité" /></SelectTrigger><SelectContent>{data.activities.map(activity => <SelectItem key={activity.id} value={String(activity.id)}>{activity.title}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Membre</Label><Select value={staffId} onValueChange={setStaffId}><SelectTrigger><SelectValue placeholder="Animateur ou volontaire" /></SelectTrigger><SelectContent>{data.staff.map(staff => <SelectItem key={staff.id} value={String(staff.id)}>{staff.name} · {roleLabels[staff.role]}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Responsabilité</Label><Select value={assignmentType} onValueChange={value => setAssignmentType(value as typeof assignmentType)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{Object.entries(typeLabels).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><div className="flex items-end"><Button className="w-full rounded-xl" disabled={!activityId || !staffId || assign.isPending} onClick={() => assign.mutate({ activityId: Number(activityId), staffId: Number(staffId), assignmentType })}><Plus className="mr-2 h-4 w-4" />Affecter</Button></div></CardContent>{selectedActivity && <CardContent className="pt-0 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><CalendarClock className="h-3.5 w-3.5" />{new Date(selectedActivity.startsAt).toLocaleString("fr-FR", { dateStyle: "medium", timeStyle: "short" })}</span></CardContent>}</Card>
    <Card className="surface-card"><CardHeader><p className="eyebrow">RAPPELS INTERNES</p><CardTitle className="mt-1 text-lg">Notifications des activités à venir</CardTitle></CardHeader><CardContent className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm text-muted-foreground">Un contrôle quotidien à 07:00 UTC crée une notification pour chaque membre affecté dont l’activité débute dans le délai défini. Les rappels sont dédupliqués par affectation.</p><div className="mt-3 flex items-center gap-2"><Label htmlFor="lead-hours" className="text-xs">Anticipation</Label><select id="lead-hours" className="h-9 rounded-lg border border-border bg-background px-2 text-sm" value={leadHours} onChange={event => setLeadHours(event.target.value)}><option value="12">12 heures</option><option value="24">24 heures</option><option value="48">48 heures</option><option value="72">72 heures</option></select>{reminderSettings.data?.enabled && <Badge className="bg-emerald-500/12 text-emerald-700 dark:text-emerald-300">Actifs</Badge>}</div></div><Button className="rounded-xl" variant={reminderSettings.data?.enabled ? "outline" : "default"} disabled={configureReminders.isPending} onClick={() => configureReminders.mutate({ enabled: !reminderSettings.data?.enabled, leadHours: Number(leadHours) })}><BellRing className="mr-2 h-4 w-4" />{reminderSettings.data?.enabled ? "Désactiver les rappels" : "Activer les rappels"}</Button></CardContent></Card>
    <Card className="surface-card overflow-hidden"><CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">AFFECTATIONS</p><CardTitle className="mt-1 text-lg">Planning des membres affectés</CardTitle></div><div className="flex flex-wrap gap-1 rounded-xl bg-muted p-1">{(["all", "upcoming", "current", "past"] as const).map(filter => <button key={filter} onClick={() => setAssignmentFilter(filter)} className={`rounded-lg px-2.5 py-1.5 text-xs font-medium ${assignmentFilter === filter ? "bg-card text-foreground shadow-sm" : "text-muted-foreground"}`}>{({ all: "Toutes", upcoming: "À venir", current: "Aujourd’hui", past: "Passées" } as Record<string, string>)[filter]}</button>)}</div></CardHeader><CardContent className="space-y-3">{visibleAssignments.length ? visibleAssignments.map(assignment => <article key={assignment.id} className="flex flex-col gap-3 rounded-2xl border border-border/70 p-4 md:flex-row md:items-center"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><UsersRound className="h-4 w-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{assignment.activityTitle}</p><Badge variant="secondary">{typeLabels[assignment.assignmentType]}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{assignment.staffName} · {roleLabels[assignment.staffRole]} · {new Date(assignment.activityStartsAt!).toLocaleString("fr-FR", { dateStyle: "medium", timeStyle: "short" })}</p></div><Button variant="outline" size="sm" className="rounded-lg text-destructive hover:text-destructive" disabled={remove.isPending} onClick={() => { if (window.confirm(`Retirer ${assignment.staffName} de l’activité « ${assignment.activityTitle} » ?`)) remove.mutate({ id: assignment.id }); }}><Trash2 className="mr-1.5 h-3.5 w-3.5" />Retirer</Button></article>) : <div className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">Aucune affectation dans cette vue.</div>}</CardContent></Card>
  </div>;
}
