import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowUpRight, CalendarClock, CheckCircle2, CircleAlert, Clock3, HeartPulse, ShieldCheck, UsersRound } from "lucide-react";
import { useState } from "react";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useLocation } from "wouter";

type Period = "week" | "month" | "quarter";
const periodLabels: Record<Period, string> = { week: "7 jours", month: "30 jours", quarter: "90 jours" };

function MetricCard({ label, value, detail, icon: Icon, accent }: { label: string; value: number | string; detail: string; icon: typeof UsersRound; accent: string }) {
  return <Card className="metric-card overflow-hidden"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight text-foreground">{value}</p><p className="mt-2 text-xs text-muted-foreground">{detail}</p></div><span className={`grid h-10 w-10 place-items-center rounded-xl ${accent}`}><Icon className="h-4 w-4" /></span></div></CardContent></Card>;
}

export default function DashboardPage() {
  const [period, setPeriod] = useState<Period>("month");
  const [location, setLocation] = useLocation();
  const snapshot = trpc.dashboard.summary.useQuery({ period });
  const data = snapshot.data;

  if (snapshot.isLoading || !data) return <div className="space-y-6"><div className="flex items-end justify-between"><div className="space-y-2"><Skeleton className="h-5 w-32" /><Skeleton className="h-9 w-80" /></div><Skeleton className="h-10 w-56" /></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 8 }).map((_, i) => <Skeleton className="h-36 rounded-2xl" key={i} />)}</div><div className="grid gap-5 xl:grid-cols-3"><Skeleton className="h-80 rounded-2xl xl:col-span-2" /><Skeleton className="h-80 rounded-2xl" /></div></div>;
  const cards = data.cards;
  return <div className="space-y-6 md:space-y-7">
    <section className="dashboard-hero overflow-hidden rounded-3xl p-6 md:p-8">
      <div className="relative z-10 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow text-primary-foreground/70">PILOTAGE DU CENTRE</p><h2 className="mt-2 max-w-2xl text-3xl font-semibold tracking-tight text-primary-foreground md:text-4xl">Une vision claire pour accompagner chaque parcours.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-primary-foreground/75">Le point d’activité du CDEJ, des présences et des situations qui demandent une décision.</p></div><div className="flex flex-wrap gap-2 rounded-2xl bg-primary-foreground/10 p-1.5 backdrop-blur"><Button size="sm" className="rounded-xl bg-primary-foreground text-primary hover:bg-primary-foreground/90" onClick={() => setLocation("/participants")}><UsersRound className="mr-2 h-4 w-4" />Nouveau dossier</Button><Button size="sm" variant="ghost" className="rounded-xl text-primary-foreground hover:bg-primary-foreground/15 hover:text-primary-foreground" onClick={() => setLocation("/attendance")}><CheckCircle2 className="mr-2 h-4 w-4" />Saisir présences</Button></div></div>
    </section>

    <section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">INDICATEURS CLÉS</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">Situation opérationnelle</h2></div><div className="flex gap-1 rounded-xl border border-border bg-card p-1 shadow-sm">{(Object.keys(periodLabels) as Period[]).map(item => <button key={item} onClick={() => setPeriod(item)} className={`rounded-lg px-3 py-1.5 text-xs font-medium transition-colors ${period === item ? "bg-primary text-primary-foreground shadow-sm" : "text-muted-foreground hover:bg-muted"}`}>{periodLabels[item]}</button>)}</div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="Participants actifs" value={cards.participants} detail="Bénéficiaires suivis" icon={UsersRound} accent="bg-blue-500/12 text-blue-700 dark:text-blue-300" /><MetricCard label="Animateurs" value={cards.facilitators} detail={`${cards.volunteers} volontaires actifs`} icon={ShieldCheck} accent="bg-violet-500/12 text-violet-700 dark:text-violet-300" /><MetricCard label="Présents aujourd’hui" value={cards.presentToday} detail={`${cards.absentToday} absence(s) signalée(s)`} icon={CheckCircle2} accent="bg-emerald-500/12 text-emerald-700 dark:text-emerald-300" /><MetricCard label="Activités" value={`${cards.completedActivities}/${cards.plannedActivities + cards.completedActivities}`} detail="Réalisées / programmées" icon={CalendarClock} accent="bg-orange-500/12 text-orange-700 dark:text-orange-300" /><MetricCard label="Congés à traiter" value={cards.pendingLeaves} detail="En attente de décision" icon={Clock3} accent="bg-rose-500/12 text-rose-700 dark:text-rose-300" /></section>

    <section className="grid gap-5 xl:grid-cols-12">
      <Card className="surface-card xl:col-span-7"><CardHeader className="flex flex-row items-center justify-between"><div><p className="eyebrow">PRÉSENCE</p><CardTitle className="mt-1 text-lg">Rythme de participation</CardTitle></div><Badge variant="secondary" className="font-medium">Cette semaine</Badge></CardHeader><CardContent className="h-[290px] pt-0"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.attendanceChart} barGap={4}><CartesianGrid vertical={false} strokeDasharray="3 3" stroke="var(--border)" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "var(--muted-foreground)", fontSize: 12 }} /><YAxis tickLine={false} axisLine={false} width={28} tick={{ fill: "var(--muted-foreground)", fontSize: 12 }} /><Tooltip cursor={{ fill: "var(--muted)" }} contentStyle={{ borderRadius: 12, borderColor: "var(--border)", background: "var(--card)" }} /><Bar dataKey="present" name="Présents" fill="#2E7D6B" radius={[6, 6, 2, 2]} /><Bar dataKey="absent" name="Absents" fill="#D56955" radius={[6, 6, 2, 2]} /></BarChart></ResponsiveContainer></CardContent></Card>
      <Card className="surface-card xl:col-span-5"><CardHeader><p className="eyebrow">RÉPARTITION</p><CardTitle className="mt-1 text-lg">Participants par sexe</CardTitle></CardHeader><CardContent className="flex h-[290px] items-center gap-4 pt-0"><div className="h-48 min-w-0 flex-1"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.genderChart} dataKey="value" innerRadius={50} outerRadius={76} paddingAngle={5} stroke="none">{data.genderChart.map(entry => <Cell key={entry.label} fill={entry.fill} />)}</Pie><Tooltip contentStyle={{ borderRadius: 12, borderColor: "var(--border)", background: "var(--card)" }} /></PieChart></ResponsiveContainer></div><div className="space-y-3">{data.genderChart.map(entry => <div className="flex items-center gap-2" key={entry.label}><span className="h-2.5 w-2.5 rounded-full" style={{ background: entry.fill }} /><span className="text-xs text-muted-foreground">{entry.label}</span><span className="ml-auto text-sm font-semibold">{entry.value}</span></div>)}<div className="border-t border-border pt-3"><p className="text-xs text-muted-foreground">Visites santé</p><p className="mt-1 flex items-center gap-1 text-lg font-semibold"><HeartPulse className="h-4 w-4 text-rose-500" />{cards.healthVisits}</p></div></div></CardContent></Card>
    </section>

    <section className="grid gap-5 xl:grid-cols-12"><Card className="surface-card xl:col-span-5"><CardHeader><p className="eyebrow">GROUPES</p><CardTitle className="mt-1 text-lg">Répartition par accompagnement</CardTitle></CardHeader><CardContent className="space-y-4">{data.groups.map((group, index) => { const max = Math.max(...data.groups.map(item => item.count), 1); return <div key={group.label}><div className="mb-2 flex items-center justify-between text-sm"><span className="font-medium">{group.label}</span><span className="text-muted-foreground">{group.count} participants</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full" style={{ width: `${(group.count / max) * 100}%`, backgroundColor: ["#2E7D6B", "#3E7CB1", "#D98B46"][index % 3] }} /></div></div> })}</CardContent></Card>
      <Card className="surface-card xl:col-span-7"><CardHeader className="flex flex-row items-start justify-between gap-4"><div><p className="eyebrow">VIGILANCE</p><CardTitle className="mt-1 text-lg">Alertes prioritaires</CardTitle></div><Button variant="ghost" size="sm" className="text-muted-foreground" onClick={() => setLocation("/reports")}>Voir tout <ArrowUpRight className="ml-1 h-3.5 w-3.5" /></Button></CardHeader><CardContent className="space-y-2">{data.alerts.length ? data.alerts.map(alert => <button key={alert.id} onClick={() => setLocation(alert.href)} className="flex w-full items-start gap-3 rounded-xl border border-border/70 p-3 text-left transition-colors hover:border-primary/35 hover:bg-muted/50"><span className={`mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-lg ${alert.priority === "critical" || alert.priority === "high" ? "bg-destructive/10 text-destructive" : "bg-amber-500/10 text-amber-600"}`}><CircleAlert className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block text-sm font-medium text-foreground">{alert.title}</span><span className="mt-0.5 block text-xs leading-5 text-muted-foreground">{alert.message}</span></span><ArrowUpRight className="mt-1 h-4 w-4 shrink-0 text-muted-foreground" /></button>) : <div className="py-7 text-center text-sm text-muted-foreground">Aucune alerte prioritaire.</div>}</CardContent></Card></section>
  </div>;
}
