import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, BookOpenCheck, HeartPulse, Loader2, LockKeyhole, Package, ShieldCheck, UtensilsCrossed, WalletCards } from "lucide-react";

function Header({ eyebrow, title, description, icon: Icon }: { eyebrow: string; title: string; description: string; icon: typeof BookOpenCheck }) {
  return <section className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">{eyebrow}</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span></section>;
}

export function EducationPage() {
  const records = trpc.education.list.useQuery();
  const participants = trpc.participants.list.useQuery({});
  const participantMap = new Map((participants.data ?? []).map(row => [row.id, `${row.firstName} ${row.lastName}`]));
  const statuses: Record<string, { label: string; cls: string }> = { progressing: { label: "En progression", cls: "bg-emerald-500/12 text-emerald-700" }, stable: { label: "Stable", cls: "bg-blue-500/12 text-blue-700" }, needs_support: { label: "À soutenir", cls: "bg-amber-500/12 text-amber-700" }, repeat: { label: "Redoublement", cls: "bg-rose-500/12 text-rose-700" } };
  return <div className="space-y-6"><Header eyebrow="ACCOMPAGNEMENT" title="Suivi éducatif" description="Résultats, difficultés identifiées et dispositifs d’accompagnement scolaire." icon={BookOpenCheck} /><div className="grid gap-4 sm:grid-cols-3"><Card className="metric-card"><CardContent className="p-4"><p className="text-xs text-muted-foreground">Fiches actives</p><p className="mt-1 text-2xl font-semibold">{records.data?.length ?? 0}</p></CardContent></Card><Card className="metric-card"><CardContent className="p-4"><p className="text-xs text-muted-foreground">Moyenne observée</p><p className="mt-1 text-2xl font-semibold">{records.data?.length ? (records.data.reduce((sum, item) => sum + Number(item.averageScore ?? 0), 0) / records.data.length).toFixed(1) : "—"}<span className="text-sm">/100</span></p></CardContent></Card><Card className="metric-card"><CardContent className="p-4"><p className="text-xs text-muted-foreground">Accompagnement requis</p><p className="mt-1 text-2xl font-semibold">{records.data?.filter(item => item.resultStatus === "needs_support").length ?? 0}</p></CardContent></Card></div><Card className="surface-card overflow-hidden"><CardHeader className="border-b border-border/70"><CardTitle className="text-base">Historique scolaire</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Participant</TableHead><TableHead>Période</TableHead><TableHead>Moyenne</TableHead><TableHead>Situation</TableHead><TableHead>Plan d’accompagnement</TableHead></TableRow></TableHeader><TableBody>{records.isLoading ? <TableRow><TableCell colSpan={5} className="h-40 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin" /></TableCell></TableRow> : (records.data ?? []).map(record => <TableRow key={record.id}><TableCell className="font-medium">{participantMap.get(record.participantId) ?? `Participant #${record.participantId}`}</TableCell><TableCell>{record.termLabel}</TableCell><TableCell className="font-semibold">{record.averageScore ?? "—"}</TableCell><TableCell><Badge className={statuses[record.resultStatus].cls}>{statuses[record.resultStatus].label}</Badge></TableCell><TableCell className="max-w-sm text-sm text-muted-foreground">{record.supportPlan ?? record.difficulties ?? "—"}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card></div>;
}

export function HealthPage() {
  const records = trpc.health.list.useQuery({});
  const participants = trpc.participants.list.useQuery({});
  const participantMap = new Map((participants.data ?? []).map(row => [row.id, `${row.firstName} ${row.lastName}`]));
  const denied = Boolean(records.error);
  return <div className="space-y-6"><Header eyebrow="CONFIDENTIEL" title="Suivi santé" description="Données sanitaires limitées aux rôles explicitement autorisés et tracées dans le journal d’audit." icon={HeartPulse} /><Card className="border-primary/25 bg-primary/[0.045]"><CardContent className="flex gap-3 p-4"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><div><p className="text-sm font-medium">Accès sensible appliqué côté serveur</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Les animateurs, coordinateurs et pasteur autorisés peuvent consulter ce module. Les informations confidentielles ne sont jamais chargées pour les rôles non autorisés.</p></div></CardContent></Card>{denied ? <Card className="surface-card"><CardContent className="grid min-h-64 place-items-center p-6 text-center"><div><LockKeyhole className="mx-auto h-8 w-8 text-muted-foreground" /><h3 className="mt-4 font-semibold">Accès limité</h3><p className="mt-2 max-w-sm text-sm text-muted-foreground">Votre rôle ne permet pas de consulter les dossiers de santé.</p></div></CardContent></Card> : <Card className="surface-card overflow-hidden"><CardHeader className="border-b border-border/70"><CardTitle className="text-base">Consultations enregistrées</CardTitle></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Participant</TableHead><TableHead>Date</TableHead><TableHead>Type</TableHead><TableHead>Synthèse</TableHead><TableHead>Traitement / référence</TableHead></TableRow></TableHeader><TableBody>{records.isLoading ? <TableRow><TableCell colSpan={5} className="h-40 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin" /></TableCell></TableRow> : (records.data ?? []).map(record => <TableRow key={record.id}><TableCell className="font-medium">{participantMap.get(record.participantId) ?? `Participant #${record.participantId}`}</TableCell><TableCell>{new Date(record.visitAt).toLocaleDateString("fr-FR")}</TableCell><TableCell><Badge variant="outline" className="font-normal">{record.visitType}</Badge></TableCell><TableCell className="max-w-sm text-sm text-muted-foreground">{record.summary}</TableCell><TableCell className="text-sm text-muted-foreground">{record.treatment ?? record.referral ?? "—"}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}</div>;
}

export function NutritionPage() {
  const records = trpc.nutrition.list.useQuery();
  return <div className="space-y-6"><Header eyebrow="ALIMENTATION" title="Nutrition" description="Menus, repas servis et observations nutritionnelles du centre." icon={UtensilsCrossed} /><div className="grid gap-4 sm:grid-cols-3"><Card className="metric-card"><CardContent className="p-4"><p className="text-xs text-muted-foreground">Repas enregistrés</p><p className="mt-1 text-2xl font-semibold">{records.data?.length ?? 0}</p></CardContent></Card><Card className="metric-card"><CardContent className="p-4"><p className="text-xs text-muted-foreground">Bénéficiaires servis</p><p className="mt-1 text-2xl font-semibold">{records.data?.reduce((sum, record) => sum + record.servedCount, 0) ?? 0}</p></CardContent></Card><Card className="metric-card"><CardContent className="p-4"><p className="text-xs text-muted-foreground">Dernier menu</p><p className="mt-1 text-sm font-medium">{records.data?.[0]?.menu ?? "À planifier"}</p></CardContent></Card></div><Card className="surface-card"><CardHeader><CardTitle className="text-base">Journal des repas</CardTitle></CardHeader><CardContent className="space-y-3">{records.isLoading ? <Loader2 className="mx-auto my-10 h-5 w-5 animate-spin" /> : (records.data ?? []).map(record => <div className="flex flex-col gap-3 rounded-xl border border-border/70 p-4 md:flex-row md:items-center" key={record.id}><div className="grid h-10 w-10 place-items-center rounded-xl bg-amber-500/10 text-amber-700"><UtensilsCrossed className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="font-medium">{record.mealType}</p><p className="text-xs text-muted-foreground">{new Date(record.mealDate).toLocaleDateString("fr-FR")} · {record.servedCount} servi(s)</p></div><p className="text-sm text-muted-foreground">{record.menu ?? "Menu non renseigné"}</p></div>)}</CardContent></Card></div>;
}

export function InventoryPage() {
  const inventory = trpc.inventory.list.useQuery();
  const suppliers = trpc.suppliers.list.useQuery();
  return <div className="space-y-6"><Header eyebrow="RESSOURCES" title="Stocks & fournisseurs" description="Suivi des articles, seuils d’alerte et prestataires du CDEJ." icon={Package} /><Card className="border-amber-500/30 bg-amber-500/[0.06]"><CardContent className="flex items-center gap-3 p-4"><AlertTriangle className="h-5 w-5 text-amber-600" /><p className="text-sm">{(inventory.data ?? []).filter(item => item.isLow).length} article(s) demandent une attention immédiate.</p></CardContent></Card><Card className="surface-card overflow-hidden"><CardHeader className="border-b border-border/70"><CardTitle className="text-base">Stock disponible</CardTitle></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Article</TableHead><TableHead>Catégorie</TableHead><TableHead>Disponible</TableHead><TableHead>Seuil</TableHead><TableHead>Fournisseur</TableHead><TableHead>État</TableHead></TableRow></TableHeader><TableBody>{inventory.isLoading ? <TableRow><TableCell colSpan={6} className="h-40 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin" /></TableCell></TableRow> : (inventory.data ?? []).map(item => <TableRow key={item.id}><TableCell><p className="font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{item.sku}</p></TableCell><TableCell><Badge variant="outline" className="font-normal">{item.category}</Badge></TableCell><TableCell className="font-semibold">{item.quantity} {item.unit}</TableCell><TableCell className="text-muted-foreground">{item.alertThreshold} {item.unit}</TableCell><TableCell className="text-sm text-muted-foreground">{item.supplierName}</TableCell><TableCell>{item.isLow ? <Badge className="bg-destructive/10 text-destructive"><AlertTriangle className="mr-1 h-3 w-3" />Stock bas</Badge> : <Badge className="bg-emerald-500/12 text-emerald-700">Suffisant</Badge>}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card className="surface-card"><CardHeader><CardTitle className="text-base">Répertoire fournisseurs</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{suppliers.isLoading ? <Loader2 className="mx-auto my-6 h-5 w-5 animate-spin" /> : (suppliers.data ?? []).map(supplier => <article className="rounded-xl border border-border/70 p-4" key={supplier.id}><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{supplier.name}</p><p className="mt-1 text-xs text-muted-foreground">{supplier.category ?? "Catégorie non définie"}</p></div><Badge variant="outline" className="font-normal">Fournisseur</Badge></div><div className="mt-4 grid gap-1 text-sm text-muted-foreground"><span>{supplier.contactName ?? "Contact à renseigner"}</span><span>{supplier.phone ?? "Téléphone non renseigné"}</span><span>{supplier.email ?? "Email non renseigné"}</span></div></article>)}</CardContent></Card></div>;
}

export function FinancePage() {
  const finance = trpc.finance.list.useQuery();
  const isDenied = Boolean(finance.error);
  const income = (finance.data ?? []).filter(row => row.type === "income").reduce((sum, row) => sum + Number(row.amount), 0);
  const expenses = (finance.data ?? []).filter(row => row.type === "expense").reduce((sum, row) => sum + Number(row.amount), 0);
  return <div className="space-y-6"><Header eyebrow="ACCÈS RESTREINT" title="Finances" description="Recettes, dépenses et pièces justificatives, réservées aux responsables habilités." icon={WalletCards} />{isDenied ? <Card className="surface-card"><CardContent className="grid min-h-72 place-items-center p-6 text-center"><div><LockKeyhole className="mx-auto h-8 w-8 text-muted-foreground" /><h3 className="mt-4 font-semibold">Données financières protégées</h3><p className="mt-2 max-w-md text-sm leading-6 text-muted-foreground">Votre compte ne dispose pas de l’autorisation pour ce module. Le contrôle est effectué par le serveur, pas seulement par l’interface.</p></div></CardContent></Card> : <><div className="grid gap-4 sm:grid-cols-3"><Card className="metric-card"><CardContent className="p-4"><p className="text-xs text-muted-foreground">Recettes</p><p className="mt-1 flex items-center gap-1 text-2xl font-semibold text-emerald-700"><ArrowUpRight className="h-5 w-5" />{income.toLocaleString("fr-FR")} $</p></CardContent></Card><Card className="metric-card"><CardContent className="p-4"><p className="text-xs text-muted-foreground">Dépenses</p><p className="mt-1 flex items-center gap-1 text-2xl font-semibold text-rose-700"><ArrowDownRight className="h-5 w-5" />{expenses.toLocaleString("fr-FR")} $</p></CardContent></Card><Card className="metric-card"><CardContent className="p-4"><p className="text-xs text-muted-foreground">Solde net</p><p className="mt-1 text-2xl font-semibold">{(income - expenses).toLocaleString("fr-FR")} $</p></CardContent></Card></div><Card className="surface-card overflow-hidden"><CardHeader className="border-b border-border/70"><CardTitle className="text-base">Mouvements récents</CardTitle></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Nature</TableHead><TableHead>Catégorie</TableHead><TableHead>Description</TableHead><TableHead className="text-right">Montant</TableHead></TableRow></TableHeader><TableBody>{finance.isLoading ? <TableRow><TableCell colSpan={5} className="h-40 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin" /></TableCell></TableRow> : (finance.data ?? []).map(item => <TableRow key={item.id}><TableCell>{new Date(item.transactionDate).toLocaleDateString("fr-FR")}</TableCell><TableCell><Badge className={item.type === "income" ? "bg-emerald-500/12 text-emerald-700" : "bg-rose-500/12 text-rose-700"}>{item.type === "income" ? "Recette" : "Dépense"}</Badge></TableCell><TableCell>{item.category}</TableCell><TableCell className="max-w-sm text-sm text-muted-foreground">{item.description}</TableCell><TableCell className="text-right font-semibold">{Number(item.amount).toLocaleString("fr-FR")} {item.currency}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></>}</div>;
}
