import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { trpc } from "@/lib/trpc";
import { Archive, Download, FileSpreadsheet, Filter, Loader2, Plus, Search, Upload } from "lucide-react";
import { FormEvent, useMemo, useRef, useState } from "react";
import * as XLSX from "xlsx";
import { toast } from "sonner";
import { useLocation } from "wouter";

const statusLabel: Record<string, string> = { active: "Actif", paused: "En pause", graduated: "Sorti", archived: "Archivé" };
const roleBadge = (status: string) => status === "active" ? "bg-emerald-500/12 text-emerald-700 dark:text-emerald-300" : status === "archived" ? "bg-muted text-muted-foreground" : "bg-amber-500/12 text-amber-700 dark:text-amber-300";
type ImportRow = { participantCode: string; firstName: string; lastName: string; gender: "female" | "male" | "other"; birthDate: Date; school?: string; classLevel?: string; guardianName?: string; guardianPhone?: string };

function normalizeHeader(value: unknown) { return String(value ?? "").toLocaleLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]/g, ""); }
function mapImportRows(rows: Array<Record<string, unknown>>) { const issues: string[] = []; const mapped: ImportRow[] = []; rows.forEach((row, index) => { const lookup = (aliases: string[]) => { const key = Object.keys(row).find(column => aliases.includes(normalizeHeader(column))); return key ? String(row[key] ?? "").trim() : ""; }; const participantCode = lookup(["identifiant", "id", "code", "participantcode", "numero"]); const firstName = lookup(["prenom", "firstname"]); const lastName = lookup(["nom", "lastname"]); const birth = lookup(["datedenaissance", "birthdate", "naissance"]); const rawGender = lookup(["sexe", "gender"]).toLocaleLowerCase(); const gender = rawGender.startsWith("f") ? "female" : rawGender.startsWith("m") || rawGender.startsWith("g") ? "male" : "other"; const parsedBirth = new Date(`${birth}T12:00:00`); if (!participantCode || !firstName || !lastName || Number.isNaN(parsedBirth.getTime())) { issues.push(`Ligne ${index + 2} : identifiant, prénom, nom ou date de naissance invalide.`); return; } mapped.push({ participantCode, firstName, lastName, gender, birthDate: parsedBirth, school: lookup(["ecole", "school"]) || undefined, classLevel: lookup(["classe", "classlevel", "niveau"]) || undefined, guardianName: lookup(["parent", "tuteur", "guardianname"]) || undefined, guardianPhone: lookup(["contact", "telephone", "phone", "guardianphone"]) || undefined }); }); return { mapped, issues }; }

function downloadCsv(rows: Array<Record<string, string | number>>) {
  const headers = Object.keys(rows[0] ?? {});
  const csv = [headers.join(","), ...rows.map(row => headers.map(header => `"${String(row[header] ?? "").replaceAll('"', '""')}"`).join(","))].join("\n");
  const url = URL.createObjectURL(new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8" }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = "participants-cdej.csv"; anchor.click(); URL.revokeObjectURL(url);
}

export default function ParticipantsPage() {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<string>("all");
  const [dialogOpen, setDialogOpen] = useState(false);
  const [importOpen, setImportOpen] = useState(false);
  const [importPreview, setImportPreview] = useState<Array<Record<string, unknown>>>([]);
  const [importRows, setImportRows] = useState<ImportRow[]>([]);
  const [importIssues, setImportIssues] = useState<string[]>([]);
  const [importSourceName, setImportSourceName] = useState("");
  const [, setLocation] = useLocation();
  const importRef = useRef<HTMLInputElement>(null);
  const input = useMemo(() => ({ query: query || undefined, status: status === "all" ? undefined : status as "active" | "paused" | "graduated" | "archived" }), [query, status]);
  const directory = trpc.directory.assignments.useQuery();
  const participants = trpc.participants.list.useQuery(input);
  const utils = trpc.useUtils();
  const archive = trpc.participants.archive.useMutation({ onSuccess: () => { toast.success("Le dossier a été archivé."); utils.participants.list.invalidate(); } });
  const create = trpc.participants.create.useMutation({ onSuccess: () => { toast.success("Participant créé avec succès."); setDialogOpen(false); utils.participants.list.invalidate(); } });
  const importBatch = trpc.participants.importBatch.useMutation({ onSuccess: result => { toast.success(`${result.created} dossier(s) importé(s), ${result.skippedDuplicates} doublon(s) ignoré(s).`); setImportOpen(false); utils.participants.list.invalidate(); } });
  const records = participants.data ?? [];

  const exportRows = () => records.map(person => ({ Identifiant: person.participantCode, Nom: person.lastName, Prénom: person.firstName, Sexe: person.gender === "female" ? "F" : "M", Âge: person.age, Groupe: person.groupName, Animateur: person.facilitatorName, École: person.school ?? "", Statut: statusLabel[person.status] }));
  const exportExcel = () => { const worksheet = XLSX.utils.json_to_sheet(exportRows()); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, "Participants"); XLSX.writeFile(workbook, "participants-cdej.xlsx"); };
  const handleImportFile = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = event => { try { const workbook = XLSX.read(event.target?.result, { type: "array" }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: "" }); const conversion = mapImportRows(rows); setImportPreview(rows.slice(0, 5)); setImportRows(conversion.mapped); setImportIssues(conversion.issues.slice(0, 5)); setImportSourceName(file.name); setImportOpen(true); } catch { toast.error("Le fichier n’a pas pu être lu."); } }; reader.readAsArrayBuffer(file); };

  return <div className="space-y-6"><section className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">DOSSIERS BÉNÉFICIAIRES</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">Participants</h2><p className="mt-1 text-sm text-muted-foreground">Profils, affectations, scolarité et historique de suivi.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" className="rounded-xl" onClick={() => importRef.current?.click()}><Upload className="mr-2 h-4 w-4" />Importer</Button><input ref={importRef} className="hidden" type="file" accept=".csv,.xlsx,.xls" onChange={event => handleImportFile(event.target.files?.[0])} /><Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogTrigger asChild><Button className="rounded-xl"><Plus className="mr-2 h-4 w-4" />Nouveau participant</Button></DialogTrigger><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Créer un dossier participant</DialogTitle><DialogDescription>Les champs essentiels sont enregistrés dans le dossier central du CDEJ.</DialogDescription></DialogHeader><ParticipantForm groups={directory.data?.groups ?? []} facilitators={directory.data?.facilitators ?? []} onSubmit={values => create.mutate(values)} isPending={create.isPending} /></DialogContent></Dialog></div></section>
    <Card className="surface-card"><CardContent className="p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Nom, identifiant, école…" className="h-10 rounded-xl pl-9" /></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="h-10 w-full rounded-xl lg:w-44"><Filter className="mr-2 h-4 w-4" /><SelectValue placeholder="Statut" /></SelectTrigger><SelectContent><SelectItem value="all">Tous les statuts</SelectItem><SelectItem value="active">Actifs</SelectItem><SelectItem value="paused">En pause</SelectItem><SelectItem value="graduated">Sortis</SelectItem><SelectItem value="archived">Archivés</SelectItem></SelectContent></Select><Button variant="outline" className="h-10 rounded-xl" onClick={() => downloadCsv(exportRows())}><Download className="mr-2 h-4 w-4" />CSV</Button><Button variant="outline" className="h-10 rounded-xl" onClick={exportExcel}><FileSpreadsheet className="mr-2 h-4 w-4" />Excel</Button></div></CardContent></Card>
    <Card className="surface-card overflow-hidden"><CardHeader className="flex flex-row items-center justify-between border-b border-border/70"><div><CardTitle className="text-base">Répertoire des participants</CardTitle><p className="mt-1 text-xs text-muted-foreground">{records.length} dossier(s) affiché(s)</p></div><Badge variant="secondary">Données de démonstration fictives</Badge></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Participant</TableHead><TableHead>Groupe</TableHead><TableHead>Animateur</TableHead><TableHead>École</TableHead><TableHead>Statut</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{participants.isLoading ? <TableRow><TableCell colSpan={6} className="h-40 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin text-muted-foreground" /></TableCell></TableRow> : records.length ? records.map(person => <TableRow key={person.id}><TableCell><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-primary/10 text-xs font-bold text-primary">{person.firstName[0]}{person.lastName[0]}</div><div><p className="font-medium">{person.firstName} {person.lastName}</p><p className="text-xs text-muted-foreground">{person.participantCode} · {person.age} ans</p></div></div></TableCell><TableCell><Badge variant="outline" className="font-normal">{person.groupName}</Badge></TableCell><TableCell className="text-sm text-muted-foreground">{person.facilitatorName}</TableCell><TableCell className="text-sm text-muted-foreground">{person.school ?? "—"}</TableCell><TableCell><Badge className={roleBadge(person.status)}>{statusLabel[person.status]}</Badge></TableCell><TableCell className="text-right"><Button size="sm" variant="ghost" className="mr-1 text-primary" onClick={() => setLocation(`/participants/${person.id}`)}>Ouvrir</Button>{person.status !== "archived" && <Button size="sm" variant="ghost" className="text-muted-foreground hover:text-destructive" disabled={archive.isPending} onClick={() => { if (window.confirm(`Archiver le dossier de ${person.firstName} ${person.lastName} ? Cette action conserve l’historique mais retire le dossier du suivi actif.`)) archive.mutate({ id: person.id }); }}><Archive className="mr-1.5 h-3.5 w-3.5" />Archiver</Button>}</TableCell></TableRow>) : <TableRow><TableCell colSpan={6} className="h-40 text-center text-sm text-muted-foreground">Aucun participant ne correspond aux filtres.</TableCell></TableRow>}</TableBody></Table></div></CardContent></Card>
    <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Prévisualisation de l’import</DialogTitle><DialogDescription>Le mapping automatique reconnaît les colonnes courantes. Les lignes incomplètes sont signalées et les identifiants existants ne sont jamais écrasés.</DialogDescription></DialogHeader><div className="grid grid-cols-3 gap-3"><div className="rounded-xl bg-primary/8 p-3"><p className="text-xs text-muted-foreground">Lignes reconnues</p><p className="mt-1 text-xl font-semibold">{importRows.length}</p></div><div className="rounded-xl bg-amber-500/8 p-3"><p className="text-xs text-muted-foreground">À corriger</p><p className="mt-1 text-xl font-semibold">{importIssues.length}</p></div><div className="rounded-xl bg-muted p-3"><p className="text-xs text-muted-foreground">Source</p><p className="mt-1 truncate text-sm font-semibold">{importSourceName}</p></div></div>{importIssues.length ? <div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-3 text-xs text-amber-800 dark:text-amber-300">{importIssues.map(issue => <p key={issue}>{issue}</p>)}</div> : null}{importPreview.length ? <div className="max-h-64 overflow-auto rounded-xl border border-border"><Table><TableHeader><TableRow>{Object.keys(importPreview[0] ?? {}).map(header => <TableHead key={header}>{header}</TableHead>)}</TableRow></TableHeader><TableBody>{importPreview.map((row, index) => <TableRow key={index}>{Object.keys(importPreview[0] ?? {}).map(header => <TableCell key={header} className="max-w-40 truncate text-xs">{String(row[header] ?? "")}</TableCell>)}</TableRow>)}</TableBody></Table></div> : null}<div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setImportOpen(false)}>Fermer</Button><Button disabled={!importRows.length || importBatch.isPending} onClick={() => importBatch.mutate({ rows: importRows, sourceName: importSourceName })}>{importBatch.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Importer sans écraser</Button></div></DialogContent></Dialog>
  </div>;
}

function ParticipantForm({ groups, facilitators, onSubmit, isPending }: { groups: Array<{ id: number; name: string }>; facilitators: Array<{ id: number; name: string }>; onSubmit: (value: { participantCode: string; firstName: string; lastName: string; gender: "female" | "male" | "other"; birthDate: Date; school?: string; classLevel?: string; guardianName?: string; guardianPhone?: string; groupId?: number; facilitatorId?: number }) => void; isPending: boolean }) {
  const [gender, setGender] = useState<"female" | "male" | "other">("female");
  const [groupId, setGroupId] = useState<string>("");
  const [facilitatorId, setFacilitatorId] = useState<string>("");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const birth = form.get("birthDate")?.toString(); if (!birth) return toast.error("La date de naissance est requise."); onSubmit({ participantCode: String(form.get("participantCode")), firstName: String(form.get("firstName")), lastName: String(form.get("lastName")), gender, birthDate: new Date(`${birth}T12:00:00`), school: String(form.get("school") || "") || undefined, classLevel: String(form.get("classLevel") || "") || undefined, guardianName: String(form.get("guardianName") || "") || undefined, guardianPhone: String(form.get("guardianPhone") || "") || undefined, groupId: groupId ? Number(groupId) : undefined, facilitatorId: facilitatorId ? Number(facilitatorId) : undefined }); };
  return <form className="grid gap-4 md:grid-cols-2" onSubmit={submit}><div className="space-y-1.5"><Label htmlFor="participantCode">Identifiant</Label><Input id="participantCode" name="participantCode" defaultValue="P-2026-" required /></div><div className="space-y-1.5"><Label>Sexe</Label><Select value={gender} onValueChange={value => setGender(value as typeof gender)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="female">Fille</SelectItem><SelectItem value="male">Garçon</SelectItem><SelectItem value="other">Autre</SelectItem></SelectContent></Select></div><div className="space-y-1.5"><Label htmlFor="firstName">Prénom</Label><Input id="firstName" name="firstName" required /></div><div className="space-y-1.5"><Label htmlFor="lastName">Nom</Label><Input id="lastName" name="lastName" required /></div><div className="space-y-1.5"><Label htmlFor="birthDate">Date de naissance</Label><Input id="birthDate" name="birthDate" type="date" required /></div><div className="space-y-1.5"><Label htmlFor="school">École</Label><Input id="school" name="school" /></div><div className="space-y-1.5"><Label>Groupe</Label><Select value={groupId} onValueChange={setGroupId}><SelectTrigger><SelectValue placeholder="Choisir" /></SelectTrigger><SelectContent>{groups.map(group => <SelectItem key={group.id} value={String(group.id)}>{group.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label>Animateur responsable</Label><Select value={facilitatorId} onValueChange={setFacilitatorId}><SelectTrigger><SelectValue placeholder="Choisir" /></SelectTrigger><SelectContent>{facilitators.map(person => <SelectItem key={person.id} value={String(person.id)}>{person.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-1.5"><Label htmlFor="guardianName">Parent / tuteur</Label><Input id="guardianName" name="guardianName" /></div><div className="space-y-1.5"><Label htmlFor="guardianPhone">Contact du tuteur</Label><Input id="guardianPhone" name="guardianPhone" /></div><div className="md:col-span-2 flex justify-end gap-2 border-t border-border pt-4"><Button type="submit" disabled={isPending}>{isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Enregistrer le dossier</Button></div></form>;
}
